all: exo2 exo3 exo4 exo5 exo6

exo2:
	g++ exo2.cpp -o exo2

exo3:
	g++ exo3.cpp -o exo3

exo4:
	g++ exo4.cpp -o exo4

exo5:
	g++ exo5.cpp -o exo5

exo6:
	g++ exo6.cpp -o exo6

clean:
	rm exo2
	rm exo3
	rm exo4
	rm exo5
	rm exo6