all : exo1 exo2 exo3 exo4 exo5 exo6

exo1: exo1.cpp
	g++ $< -o $@

exo2: exo2.cpp
	g++ $< -o $@

exo3: exo3.cpp
	g++ $< -o $@

exo4: exo4.cpp
	g++ $< -o $@

exo5: exo5.cpp
	g++ $< -o $@

exo6: exo6.cpp
	g++ $< -o $@

clean:
	rm exo1
	rm exo2
	rm exo3
	rm exo4
	rm exo5
	rm exo6